from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from backend.core.database import get_db
from backend.repositories.internal_postgres_repo import InternalPostgresRepository
from backend.schemas.internal_postgres_schema import (
    InternalClassRosterOut,
    InternalHistoryOut,
    InternalProfileOut,
    InternalQuizAttemptIn,
    InternalQuizAttemptOut,
)
from backend.services.internal_postgres_service import (
    InternalPostgresService,
    InternalProfileNotFoundError,
)

router = APIRouter(prefix="/internal/postgres", tags=["Internal Postgres Contracts"])


def _service(db: Session) -> InternalPostgresService:
    return InternalPostgresService(InternalPostgresRepository(db))


@router.get("/profile", response_model=InternalProfileOut)
def get_internal_profile(
    student_id: UUID,
    db: Session = Depends(get_db)
):
    """
    GET /api/v1/internal/postgres/profile
    Internal contract used by the RAG/Graph engine to fetch student context.
    """
    try:
        return _service(db).get_profile(student_id=student_id)
    except InternalProfileNotFoundError as e:
        raise HTTPException(status_code=404, detail=str(e))


@router.get("/history", response_model=InternalHistoryOut)
def get_internal_history(
    student_id: UUID,
    session_id: UUID,
    db: Session = Depends(get_db)
):
    """
    GET /api/v1/internal/postgres/history
    Internal contract to fetch student activity history for LLM personalization.
    Requires both student_id and session_id as per service logic.
    """
    return _service(db).get_history(student_id=student_id, session_id=session_id)


@router.post("/quiz-attempt", response_model=InternalQuizAttemptOut)
def create_internal_quiz_attempt(
    attempt_data: InternalQuizAttemptIn,
    db: Session = Depends(get_db)
):
    """
    POST /api/v1/internal/postgres/quiz-attempt
    Saves a quiz attempt generated by the AI Core directly to the database.
    """
    try:
        return _service(db).store_quiz_attempt(payload=attempt_data)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/class-roster", response_model=InternalClassRosterOut)
def get_class_roster(
    class_id: UUID,
    db: Session = Depends(get_db)
):
    """
    GET /api/v1/internal/postgres/class-roster
    Returns the list of students in a class for batch processing tasks.
    """
    return _service(db).get_class_roster(class_id=class_id)
