from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from uuid import UUID
from typing import List

from backend.core.database import get_db
from backend.schemas.internal_postgres_schema import (
    InternalProfileOut,
    InternalHistoryOut,
    InternalQuizAttemptIn,
    InternalQuizAttemptOut,
    InternalClassRosterOut
)
from backend.services.internal_postgres_service import internal_postgres_service

router = APIRouter(prefix="/internal/postgres", tags=["Internal Postgres Contracts"])

@router.get("/profile", response_model=InternalProfileOut)
def get_internal_profile(
    student_id: UUID,
    db: Session = Depends(get_db)
):
    """
    GET /api/v1/internal/postgres/profile
    Internal contract used by the RAG/Graph engine to fetch student context.
    """
    try:
        # get_profile in the service handles the lookup and raises error if not found
        return internal_postgres_service.get_profile(student_id=student_id)
    except Exception as e:
        raise HTTPException(status_code=404, detail=str(e))

@router.get("/history", response_model=InternalHistoryOut)
def get_internal_history(
    student_id: UUID,
    session_id: UUID,
    db: Session = Depends(get_db)
):
    """
    GET /api/v1/internal/postgres/history
    Internal contract to fetch student activity history for LLM personalization.
    Requires both student_id and session_id as per service logic.
    """
    return internal_postgres_service.get_history(student_id=student_id, session_id=session_id)

@router.post("/quiz-attempt", response_model=InternalQuizAttemptOut)
def create_internal_quiz_attempt(
    attempt_data: InternalQuizAttemptIn,
    db: Session = Depends(get_db)
):
    """
    POST /api/v1/internal/postgres/quiz-attempt
    Saves a quiz attempt generated by the AI Core directly to the database.
    """
    try:
        return internal_postgres_service.store_quiz_attempt(payload=attempt_data)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/class-roster", response_model=InternalClassRosterOut)
def get_class_roster(
    class_id: UUID,
    db: Session = Depends(get_db)
):
    """
    GET /api/v1/internal/postgres/class-roster
    Returns the list of students in a class for batch processing tasks.
    """
    return internal_postgres_service.get_class_roster(class_id=class_id)